# Generated by Django 3.1.3 on 2022-05-17 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_id', models.CharField(blank=True, max_length=9, null=True)),
                ('original_crime_type_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Crime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('report_date', models.DateField(blank=True, max_length=255, null=True)),
                ('call_date', models.DateField(blank=True, max_length=255, null=True)),
                ('offense_date', models.DateField(blank=True, max_length=255, null=True)),
                ('call_time', models.CharField(blank=True, max_length=5, null=True)),
                ('call_date_time', models.DateField(blank=True, max_length=255, null=True)),
                ('crime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.crime')),
            ],
            options={
                'db_table': 'Date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('disposition', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_id', models.CharField(blank=True, max_length=255, null=True)),
                ('address_type', models.CharField(blank=True, max_length=255, null=True)),
                ('common_location', models.CharField(blank=True, max_length=255, null=True)),
                ('crime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.crime')),
            ],
            options={
                'db_table': 'Location',
                'managed': False,
            },
        ),
    ]
