# Generated by Django 3.1.3 on 2022-05-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_id', models.CharField(blank=True, max_length=9, null=True)),
                ('original_crime_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('report_date', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('call_date', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('offense_date', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('call_time', models.CharField(blank=True, max_length=5, null=True)),
                ('call_date_time', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('disposition', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('agency_id', models.CharField(blank=True, max_length=255, null=True)),
                ('address_type', models.CharField(blank=True, max_length=255, null=True)),
                ('common_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Crime',
                'managed': False,
            },
        ),
    ]
